### ISSUE TITLE
Variable frequency PWM

### ISSUE THREAD

**Issue by jbthomas50** [jbthomas50/voodooWaterTower#6]
write code for a PWM with a variable frequency. The analogWrite() function doesn't give the functionality we'll need for this project. We'll have to access the timer registers directly in order to change the PWM frequency so that our timing will work correctly

**Comment by jbthomas50** [comment]
I have found two options to this issue. We can access the clocks for each PWM directly and change the frequency that way, and we could wrap it in our own library (https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM), or there is a PWM frequency library that we can use that already does this for us (https://forum.arduino.cc/index.php?topic=117425.0). I haven't checked the implementation or how much functionality it has to see if it will work for us. If it doesn't have the functionality we want, we could use it as a base and add to it for our own purposes.

**Comment by Amulek1416** [comment]
Here is the webpage that goes over the low-level PWM settings:
https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM

**Comment by Amulek1416** [comment]
Since this is starting to become a pretty large project on its own, should I just turn this into its own repository and we just include the repository into this one as a dependency?

**Comment by Amulek1416** [comment]
This has become its own repository and has been moved to https://github.com/Amulek1416/low-level-PWM
